### ISSUE TITLE
Did Jon Orwant really throw and smash a mug?

### ISSUE THREAD

**Issue by stevan** [rjbs/QA-LarryWall#12]
The "smashed mug" origin of Perl 6 has passed into legend, several versions of the story exist (as with any good legend), but I would love to hear Larry recount it.

**Comment by rjbs** [comment]
I'm not sure whether this will get in, as I finish compiling questions.  Probably it will at least be referenced, but we'll see.  I wanted to make sure you got Larry's canonical telling though, in case we don't get it in the QA:

http://strangelyconsistent.org/blog/happy-10th-anniversary-perl-6
