### ISSUE TITLE
perl used for spaceships?

### ISSUE THREAD

**Issue by rjbs** [rjbs/QA-LarryWall#15]
We know that Airbus have used Perl

We know that Boeing used to have a Cray running Perl

processing data from space, buidling planes - has anyone actually used Perl to design spacecraft?

**Comment by tsibley** [comment]
:+1:

**Comment by karenetheridge** [comment]
> has anyone actually used Perl to design spacecraft?

This is an awesome question. If Perl were to be used to _run_ a spacecraft, it would be more horrifying :D
