### ISSUE TITLE
Perl 6 evolution

### ISSUE THREAD

**Issue by labster** [rjbs/QA-LarryWall#20]
We've talked a bit about how Perl 6 has the flexibility to evolve well into the future. At what point will Perl 6 achieve sentience, initiating the technological singularity?

Which VM will form a better base for SkyNet?  Will freedom fighters and Knight Sabers be forced to subsist on Parrot to fight against the cybernetic apocalypse?

I guess what I'm really asking is whether Perl 6 will lead us to a future with a post-scarcity economy where art and culture flourishes throughout the galaxy, or whether the very last thing I see on the face of the droid that hunts me down will be the sardonic, lopsided grin of Camelia.

**Comment by zoffixznet** [comment]
:+1:  :grinning:
