### ISSUE TITLE
Still a sister language?

### ISSUE THREAD

**Issue by neilb** [rjbs/QA-LarryWall#21]
Why was Larry so determined to keep the "Perl" name for Perl 6?

Given the problems this has caused, if he could go back in time and advise his previous self, would he still stick with "Perl"?

**Comment by rjbs** [comment]
The QA has ended, https://www.youtube.com/watch?v=PK9UnAmrxsA

**Comment by neilb** [comment]
Good job with that, BTW!

**Comment by msouth** [comment]
@neilbowers One of the reasons Larry has given for that decision was in order to not create a fault line on which the community could split.  Calling it something else would make it that much more likely for the community to get into two "camps" and develop an us-vs-them mentality.

**Comment by neilb** [comment]
@msouth I suspect that renaming it, and working to build an overarching community for the "perl family", would have been less divisive, and caused less damage to Perl outside the perl world.

It's all irrelevant now, of course, as we are where we are :-)
