### ISSUE TITLE
Successorship

### ISSUE THREAD

**Issue by perlpilot** [rjbs/QA-LarryWall#3]
Do you think the Perl community is in good shape to succeed you (Larry) as the keeper of the Perl languages (both Perl5 and Perl6 and any other progeny)?  That is, if you could take a peek at future Perls long after you're gone, would you recognize them as "Perl"?

**Comment by msouth** [comment]
I can think of many instances of Larry sharing design philosophy "inline" as he describes decisions about the language (see https://www.youtube.com/watch?v=mxLIQxSda0E ).  I wonder if he's ever collected that into a sort of design-of-the-design document.  That would be fun to read on its own, if it exists or were to be created, and might contribute to good (and by that I mean "Larry-like") design in post-Larry Perls.
