### ISSUE TITLE
regrets, wishes for do-overs?

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/QA-LarryWall#6]
If you could do it (perl5 and/or perl 6) all over again, what would you do differently?

or in other words, if you had a time machine, what would you go back and fix?

**Comment by zoffixznet** [comment]
:+1:

**Comment by c9s** [comment]
:+1:

**Comment by uvtc** [comment]
If he could do Perl 5 over again, it would be Perl 6, no?

I'm more interested in the answer to the Perl 6 version of the above question. Perhaps with a prelude of: Are you satisfied with Perl 6 the language? Or maybe beef that up to: is Perl 6 your favorite high-level programming language? If it is, what makes it so?
